// startup_scripts/blocks.js
StartupEvents.registry('block', event => {
  event.create('eldorado_block')
    .displayName('Eldorado Block')
    .material('metal')
    .hardness(5.0)
    .resistance(6.0)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_diamond_tool')

  event.create('eldorado_ore')
    .displayName('Eldorado Ore')
    .material('stone')
    .hardness(3.0)
    .resistance(3.0)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_diamond_tool')

  event.create('unoctanium_ore')
    .displayName('Unoctanium Ore')
    .material('stone')
    .hardness(3.0)
    .resistance(3.0)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_diamond_tool')

  event.create('unoctanium_deepslate_ore')
    .displayName('Unoctanium Deepslate Ore')
    .material('stone')
    .hardness(4.5)
    .resistance(3.0)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_diamond_tool')
})